@id = 17
@token = "ACCESS_TOKEN"

GET http://localhost:8080/books

###

POST http://localhost:8080/books
content-type: application/json

{
   // "id": 3,
    "title": "Harry Potter",
    "author": "Rowling"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "username", 
    "password": "1234"
}
###
GET http://localhost:8080/books
Authorization: Bearer ACCESS_TOKEN


###
GET https://nick-golang-api.herokuapp.com/api/books
Authorization: Bearer ACCESS_TOKEN


### test enginx integate
GET http://localhost/api/books
Authorization: Bearer ACCESS_TOKEN
###

###
DELETE  http://localhost:8080/books/{{id}}
Authorization: Bearer ACCESS_TOKEN

### test

